[package]
name = "sub-solver"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
bincode = "1.3.3"
clap = { version = "4.1.4", features = ["derive"] }
dirs = "4.0.0"
lazy_static = "1.4.0"
md5 = "0.7.0"
unidecode = "0.3.0"
